
development:
 adapter: postgresql
 encoding: unicode
 database: flu_dev
 host: localhost
 port: 5432
 pool: 5

production:
 adapter: postgresql
 encoding: unicode
 database: flu_launch
 host: localhost
 port: 5432
 pool: 5

test:
 adapter: postgresql
 encoding: unicode
 database: flu_test
 host: localhost
 port: 5432
 pool: 5