
development:
 adapter: postgresql
 encoding: unicode
 database: db
 host: localhost
 port: 5432
 pool: 5

production:
 adapter: postgresql
 encoding: unicode
 database: db
 host: localhost
 port: 5432
 pool: 5

test:
 adapter: postgresql
 encoding: unicode
 database: db
 host: localhost
 port: 5432
 pool: 5